- setup.cfg
- wsi_inference/main.py
- wsi_inference/modellib/inceptionv4.py
- wsi_inference/modellib/models.py
- wsi_inference/modellib/run_inference.py
- wsi_inference/patchlib/README.md
This makes a pretty command line interface.
Also copies in inceptionv4 module from pretrainedmodels (so we don't need to make it a dependency, because we only use this one file).
> ADD: click command line interface

- wsi_inference/convert_csv_to_geojson.py
- wsi_inference/modellib/run_inference.py
Also save all class probabilities in a single GeoJSON file (one geojson file per slide).
the command line is now
```
wsi_convert_csv_to_geojson pipeline-outputs geojson-outputs
```
> ENH: convert directory of CSVs to GeoJSON

- wsi_inference/modellib/models.py
- wsi_inference/modellib/run_inference.py
> ADD: resnet34 models for LUAD and PRAD

- wsi_inference/modellib/run_inference.py
> FIX: disable tilesource tile cache

- dockerfiles/tils.dockerfile
- dockerfiles/tumor-brca.dockerfile
- dockerfiles/tumor-luad.dockerfile
- dockerfiles/tumor-paad.dockerfile
- dockerfiles/tumor-prad.dockerfile
- wsi_inference/main.py
Dockerfiles for task-specific docker images.
> ADD: docker apps

- README.md
- scripts/README.md
- wsi_inference/convert_csv_to_sbubmi.py
- wsi_inference/main.py
- Fixes the directory structure of the outputs...
- Adds a `run_metadata.json` file in results_dir
fixes #36 
fixes #32 
fixes #14
fixes #13
> FIX: conversion script to make SBU BMI output format

- README.md
- wsinfer/cli/cli.py
- wsinfer/cli/convert_csv_to_geojson.py
- wsinfer/cli/convert_csv_to_sbubmi.py
- wsinfer/cli/infer.py
- wsinfer/cli/list_models_and_weights.py
- wsinfer/modellib/models.py
- wsinfer/patchlib/create_patches_fp.py
Adds the cli command
```
wsinfer list
```
to list all combinations of models and weights. here is output as of december 20 2022:
```
+------------------------------------------+
| MODEL               WEIGHTS              |
| ======================================== |
| inceptionv4         TCGA-BRCA-v1         |
| inceptionv4         TCGA-TILs-v1         |
| ---------------------------------------- |
| resnet34            TCGA-BRCA-v1         |
| resnet34            TCGA-LUAD-v1         |
| resnet34            TCGA-PRAD-v1         |
| ---------------------------------------- |
| resnet34_preact     TCGA-PAAD-v1         |
| ---------------------------------------- |
| vgg16_modified      TCGA-BRCA-v1         |
+------------------------------------------+
```
> ADD: 'wsinfer list' command

- .github/workflows/ci.yml
- README.md
- setup.cfg
- tests/test_all.py
This pull request adds some tests run by pytest. It adds pytest to the dev extras depenencies and runs the tests in github CI.
> ADD: pytest tests and run in CI

- README.md
- tests/test_all.py
- wsinfer/cli/infer.py
- wsinfer/modellib/models.py
- wsinfer/patchlib/create_patches_fp.py
This also changes the Weights object transform attribute to be an instance of PatchClassifcation.
> ADD: tests of patching and of run_metadata.json

- docs/conf.py
- setup.cfg
- tests/test_all.py
> FIX: add geojson validation in tests + update copyright year

- wsinfer/_patchlib/create_patches_fp.py
> divide by total time only if it is nonzero

- wsinfer/_modellib/run_inference.py
- wsinfer/cli/infer.py
fixes https://github.com/kaczmarj/wsinfer/issues/65
> print slide ids that failed patching or inference

- wsinfer/_modellib/inceptionv4_no_batchnorm.py
> use a default config for inception_v4 to prevent stderr message

- .github/workflows/ci.yml
Add a dedicated test for style and types, and move those tests out of the pytests. Also adds a test that `make html` returns a non-zero exit code.
> [CI] build docs + separate style/type tests

- tests/test_all.py
- wsinfer/cli/infer.py
> handle 'git' not being installed

- .github/workflows/ci.yml
- wsinfer/_modellib/models.py
- wsinfer/cli/infer.py
> [FIX] remove duplicate choices in 'wsinfer run' cli + clarify model-weight pairs

- wsinfer/_modellib/run_inference.py
- wsinfer/cli/infer.py
allow inference on multiple GPUs.
fixes #102
> [ENH] add multi-gpu support

- setup.cfg
- wsinfer/_modellib/run_inference.py
- wsinfer/cli/infer.py
adds `--roi-dir` to `wsinfer run`.
also adds shapely and geojson to the dependencies.
fixes #108
> [ENH] adds ability to run inference inside ROI

- docs/index.rst
- tests/test_all.py
- wsinfer/modeldefs/resnet34_tcga-prad-v1.yaml
Fixes https://github.com/SBU-BMI/wsinfer/issues/121
> replace prad label grade4+5 -> grade4or5

- tests/test_all.py
- wsinfer/_modellib/models.py
Fixes https://github.com/SBU-BMI/wsinfer/issues/116
> fix bug in setting state dict from relative path

- tests/test_all.py
- wsinfer/_modellib/models.py
- wsinfer/cli/infer.py
> handle Path instances for Weights.file

- wsinfer/_patchlib/create_patches_fp.py
- wsinfer/cli/patch.py
> fix auto-skip bug and gracefully handle failed patching

- .github/workflows/ci.yml
- Dockerfile
- README.md
- docs/conf.py
- docs/index.rst
- docs/installing.rst
- docs/qupath_ext.rst
- docs/user_guide.rst
- pyproject.toml
- wsinfer/__init__.py
- wsinfer/cli/cli.py
- wsinfer/cli/convert_csv_to_geojson.py
- wsinfer/cli/convert_csv_to_sbubmi.py
- wsinfer/cli/infer.py
- wsinfer/cli/patch.py
- wsinfer/errors.py
- wsinfer/modellib/data.py
- wsinfer/modellib/models.py
- wsinfer/modellib/run_inference.py
- wsinfer/patchlib/__init__.py
- wsinfer/patchlib/patch.py
- wsinfer/patchlib/segment.py
- wsinfer/wsi.py
Update docs to use the updated `wsinfer` command line api. Also add docstrings to more python functions.
fixes #159 
fixes #120
> DOCS: update website, docstrings, and types for upcoming 0.4.0 release

- pyproject.toml
- wsinfer/cli/infer.py
We no longer use yaml files so we can remove the pyyaml dependency.
> [ENH] rm pyyaml dep

- tests/test_all.py
- wsinfer/wsi.py
> ADD: calcuate mpp with openslide tiff tags

- docs/index.rst
- tests/test_all.py
related to https://huggingface.co/datasets/kaczmarj/wsinfer-model-zoo-json/commit/653aba1a04685a3065a8c2bfbdb0bfb09a607055
> remove vgg16 and inception breast models

- docs/conf.py
> add link to github repo in navbar

- docs/user_guide.rst
> fixed togeojson and tosbu commands

- pyproject.toml
- wsinfer/wsi.py
related to failing tests in #184
> check that page0 is TiffPage inst

- README.md
- docs/installing.rst
- docs/qupath_ext.rst
- docs/user_guide.rst
> clarify docs on gpu install + explain model output directory

- docs/_static/switcher.json
- docs/user_guide.rst
add a video walkthrough to the docs https://www.youtube.com/watch?v=0X86_A4vopw
> [DOCS] add video walkthrough to user guide + update version switcher

- wsinfer/patchlib/patch.py
- wsinfer/patchlib/segment.py
> fix types when using cv2

- .github/workflows/ci.yml
> add python 3.12 to ci
