.github/workflows/ci.yml
without `--find-links https://girder.github.io/large_image_wheels` an error is raised that `gdal-config` is not found.
=> use --find-links for pip install

Dockerfile, README.md, setup.cfg, wsi_inference/convert_csv_to_geojson.py, wsi_inference/main.py, wsi_inference/modellib/models.py, wsi_inference/modellib/run_inference.py, wsi_inference/modellib/transforms.py, wsi_inference/patchlib/create_patches_fp.py
I have uploaded the model weights to stony brook's box service. this pull request adds lazy downloading of model weights. the weights of the model are downloaded if a user requests them (similar to the behavior in `torchvision.models` and `timm`). 
also adds a functional interface to the patching command (no more subprocess in the main cli)
improve error messages (particularly if a GPU is not available)
closes #9
=> Add: model weight urls

README.md, setup.cfg, wsi_inference/convert_csv_to_sbubmi.py, wsi_inference/main.py, wsi_inference/patchlib/create_dense_patch_grid.py, wsi_inference/patchlib/create_patches_fp.py
this pull request adds:
- `wsi_convert_csv_to_sbubmi` command line program to convert the output to a format used by stony brook biomedical informatics.
- large_image tiff source to the dependencies to read multi-scale tiff images.
- add prediction on a dense grid. in other words, run model inference on all patches of an image (without the creation of a tissue mask).
=> add conversion script to sbu bmi + support multires tiff + add dense grid prediction

wsi_inference/modellib/models.py
Use 350 px patches at 0.25 mpp. Patches are 87.5 um. Fixes #18
=> FIX mpp for TCGA BRCA v1 models

wsi_inference/modellib/run_inference.py, wsi_inference/patchlib/create_patches_fp.py
We cannot work with slides that are missing spacing information, so let's skip them for now. In the future, maybe we can add a command line flag to provide spacing.
=> FIX: skip slides without spacing information

wsi_inference/modellib/run_inference.py
It is possible for patching to fail, for example because the pixel spacing is not present in the slide file. This commit modifies the inference loop to skip files that are missing their patch hdf5 files.
Fixes #24
=> skip slides with missing patch hdf5 files

README.md, wsi_inference/modellib/models.py, wsi_inference/modellib/resnet_preact.py, wsi_inference/modellib/run_inference.py
this PR 
- adds a model for detection of pancreatic adenocarcinoma. 
- adds support for 1-class model outputs, where sigmoid is used to convert logits to a probability distribution.
- implements preactivation resnet.
- removes the default weights for model loaders. now, weights need to be specified.
Closes #17 
Please see #17 for more information and a visualization of model outputs.
=> ADD: paad model

dockerfiles/tils.dockerfile, dockerfiles/tumor-brca.dockerfile, dockerfiles/tumor-luad.dockerfile, dockerfiles/tumor-paad.dockerfile, dockerfiles/tumor-prad.dockerfile
Downloaded models are made with mode 0600. This is because they start out as tempfile.NamedTemporaryFile objects, which are by default made with 0600 mode.
=> FIX: make downloaded models readable by all users

dockerfiles/tils.dockerfile, dockerfiles/tumor-brca.dockerfile, dockerfiles/tumor-luad.dockerfile, dockerfiles/tumor-paad.dockerfile, dockerfiles/tumor-prad.dockerfile, scripts/build_docker_images.sh, wsi_inference/main.py
- set the version of the base image to `v0.2.1`.
- fix the function `_in_container` to properly detect whether the code is running inside a singularity / apptainer container.
- make `--model` a required argument in `wsi_run`.
=> update model-specific docker image versions + fix _in_container + make --model required

setup.cfg, tests/test_all.py, wsinfer/cli/infer.py, wsinfer/modeldefs/inceptionv4_tcga-brca-v1.yaml, wsinfer/modeldefs/inceptionv4nobn_tcga-tils-v1.yaml, wsinfer/modeldefs/preactresnet34_tcga-paad-v1.yaml, wsinfer/modeldefs/resnet34_tcga-brca-v1.yaml, wsinfer/modeldefs/resnet34_tcga-luad-v1.yaml, wsinfer/modeldefs/resnet34_tcga-prad-v1.yaml, wsinfer/modeldefs/vgg16mod_tcga-BRCA-v1.yaml, wsinfer/modellib/inceptionv4.py, wsinfer/modellib/inceptionv4_no_batchnorm.py, wsinfer/modellib/models.py, wsinfer/modellib/resnet_preact.py, wsinfer/modellib/run_inference.py, wsinfer/modellib/vgg16mod.py
the `wsinfer run` command now accepts a `--config` option to a yaml file. the options `--model` and `--weights` are mutually exclusive with `--config`.
this is an example of a yaml config file:
```yaml
architecture: resnet34  # Must be a string.
name: TCGA-BRCA-v1  # Must be a string.
url: https://stonybrookmedicine.box.com/shared/static/dv5bxk6d15uhmcegs9lz6q70yrmwx96p.pt
url_file_name: resnet34-brca-20190613-01eaf604.pt
num_classes: 2
transform:
resize_size: 224  # Must be a single integer.
mean: [0.7238, 0.5716, 0.6779]  # Must be a list of three floats.
std: [0.1120, 0.1459, 0.1089]  # Must be a list of three floats.
patch_size_pixels: 350
spacing_um_px: 0.25
class_names:
- notumor
- tumor
```
=> ENH: use yaml config files to define models

Dockerfile, README.md, dockerfiles/tils.dockerfile, dockerfiles/tumor-brca.dockerfile, dockerfiles/tumor-luad.dockerfile, dockerfiles/tumor-paad.dockerfile, dockerfiles/tumor-prad.dockerfile, scripts/build_docker_images.sh, tests/test_all.py, wsinfer/modeldefs/inceptionv4_tcga-brca-v1.yaml, wsinfer/modeldefs/inceptionv4nobn_tcga-tils-v1.yaml, wsinfer/modeldefs/preactresnet34_tcga-paad-v1.yaml, wsinfer/modeldefs/resnet34_tcga-brca-v1.yaml, wsinfer/modeldefs/resnet34_tcga-luad-v1.yaml, wsinfer/modeldefs/resnet34_tcga-prad-v1.yaml, wsinfer/modeldefs/vgg16mod_tcga-BRCA-v1.yaml, wsinfer/modellib/models.py
Add a version key to the spec to handle updates gracefully in the future.
```yaml
version: "1.0"
```
=> ENH: update dockerfiles and add version to config spec

.github/workflows/ci.yml, setup.cfg
Adds a 'test-docker' step to CI. And fixes the path to package_data in setup.cfg.
During the creation of this PR I discovered that the 0.3.2 release wheel will not work because the tcga.csv file is not present (because package_data was not changed when I made patchlib into _patchlib). So after this PR is merged, we should release a new version and remove 0.3.2 from pypi. but the docker images work fine, so we can leave those alone. i added the 'test-package' job in ci to catch regressions in the python package. running wsinfer from a different directory (and from a non-editable install) triggered the error.
=> TST: run tests in docker image + fix setup.cfg regression

.github/workflows/ci.yml, tests/test_all.py, wsinfer/_modellib/models.py, wsinfer/_modellib/run_inference.py, wsinfer/cli/infer.py
This pr adds a `--speedup` option that jit compiles the model. tests included.
fixes #72 
fixes #70
=> ENH: add a --speedup option and tests

tests/test_all.py, wsinfer/_modellib/models.py
=> fix undefined path + add test of valid yaml config

wsinfer/_modellib/run_inference.py
=> place test_input on same device as model in jit_compile

.github/workflows/ci.yml
pytorch nightly is a moving target and things may break. we test in nightly to be able to anticipate future breaking changes. but a failure in the nightly tests should not reflect as an overall build failure.
=> allow pytest to fail in nightly

docs/cli.rst, docs/conf.py, docs/index.rst, docs/requirements.txt, setup.cfg, wsinfer/cli/cli.py, wsinfer/cli/convert_csv_to_geojson.py, wsinfer/cli/convert_csv_to_sbubmi.py, wsinfer/cli/infer.py, wsinfer/cli/list_models_and_weights.py, wsinfer/cli/patch.py
This adds auto-generated docs for the wsinfer cli. This commit also renames the subcommand cli function names, to account for https://github.com/click-contrib/sphinx-click/issues/74
fixes #76
=> add cli docs with sphinx-click

.readthedocs.yaml, docs/requirements.txt, setup.cfg
adds a `.readthedocs.yaml` config file.
=> [DOCS] fix readthedocs build by adding config

setup.cfg, tests/test_all.py, wsinfer/_patchlib/create_patches_fp.py, wsinfer/_patchlib/utils/utils.py, wsinfer/_patchlib/wsi_core/WholeSlideImage.py, wsinfer/_patchlib/wsi_core/wsi_utils.py
skip unreadable files and print a message.
this PR also 
- updates the patching progress messages to use percentages and to use the correct value of current iteration.
- adds torch and torchvision to `install_requires` in `setup.cfg`.
fixes #94
=> [FIX] do not panic on unreadable files

wsinfer/_modellib/run_inference.py
In effect disable the caching of tile source objects. This reduces the amount of open file handles.
fixes #98
=> set cache_tilesource_maximum to 1

.github/workflows/ci.yml, tests/test_all.py, wsinfer/cli/infer.py
=> write one run_metadata.json file per run

Dockerfile
=> [ENH] use pytorch 2.0.0 as base image

.gitignore, wsinfer/_modellib/run_inference.py, wsinfer/_patchlib/utils/utils.py
See https://pytorch.org/docs/stable/notes/mps.html
Testing this with one image using a Mac Studio (M1 Max) the processing time decreased from ~21 minutes to ~2 minutes.
I'm not sure if the change in `utils.py` is necessary, nor if there should be changes in other places - it looks like the report in `infer.py` should be updated if this is accepted.
Also updated `.gitignore` for more Mac (and PyCharm) friendliness.
=> Support MPS on Apple Silicon

tests/test_all.py
addresses https://github.com/SBU-BMI/wsinfer/pull/179#issuecomment-1668443083
=> skip openslide/tiffslide tests if those backends not available

wsinfer/modellib/run_inference.py
When running wsinfer in a windows subsystem for linux environment, i got the error below. Appending a tensor from the dataloader to a list can cause this issue, and cloning the tensor solves it. This commit clones the tensor.
```
RuntimeError: Too many open files. Communication with the workers is no longer possible. Please increase the limit using `ulimit -n` in the shell or change the sharing strategy by calling `torch.multiprocessing.set_sharing_strategy('file_system')` at the beginning of your code
```
related to https://github.com/pytorch/pytorch/issues/11201
=> clone batch_coords tensor to prevent Too many open files error

wsinfer/cli/infer.py, wsinfer/modellib/run_inference.py, wsinfer/patchlib/__init__.py, wsinfer/wsi.py
fixes #189 
this could also be done differently, e.g. `glob("*")` or `iterdir` + checking if `is_dir`
=> restrict wsi_dir.glob to files

.github/workflows/ci.yml, pyproject.toml, wsinfer/modellib/run_inference.py, wsinfer/wsi.py
=> test that openslide.OpenSlide is available

.vscode/settings.json, wsinfer/cli/infer.py, wsinfer/qupath.py
in some cases, it is desirable to customize the tissue segmentation parameters. the defaults may under- or over-estimate tissue.
related to #213  -- in that issue, the entire image was interpreted as tissue using the defaults. changing the binary threshold to 12 resulted in a good segmentation.
=> Add segmentation options to wsinfer run

tests/test_all.py, wsinfer/cli/convert_csv_to_sbubmi.py, wsinfer/cli/infer.py, wsinfer/cli/patch.py, wsinfer/modellib/data.py, wsinfer/modellib/run_inference.py, wsinfer/patchlib/__init__.py, wsinfer/patchlib/patch.py, wsinfer/write_geojson.py
The purpose of the PR is to clean up various issues. This PR also adds strided patches (they can be overlapped or spaced apart).
One may use overlapping patches in attempt to smooth out noise. Strided patches with holes may be useful to increase the speed of runtime. If one does not need a dense classification, then strided patches might be useful. An overlap ratio of -1 results results in 4x fewer patches.
```
wsinfer run -m breast-tumor-resnet34.tcga-brca -i slides/ -o outputs-overlap-minus1/ --patch-overlap-ratio -1
```
```
wsinfer run -m breast-tumor-resnet34.tcga-brca -i slides/ -o outputs-overlap-0.5/ --patch-overlap-ratio 0.5
```
fixes #216 
fixes #214 
fixes #205 
fixes #203 
fixes #202 
fixes #195 
fixes #185
=> Cleanup + add strided patches

README.md, docs/index.rst, wsinfer/modellib/run_inference.py, wsinfer/patchlib/segment.py
Adds disclaimer to README.md for GitHub and docs/index.rst for website.
=> [DOC] add disclaimer that this project is for academic research purposes only

.github/workflows/ci.yml, wsinfer/__init__.py, wsinfer/cli/convert_csv_to_sbubmi.py, wsinfer/modellib/data.py, wsinfer/patchlib/__init__.py, wsinfer/wsi.py
fixes #225 
this rewords the `wsinfer.wsi` namespace and introduces a new function `wsinfer.wsi.get_wsi_cls()` to get the correct constructor (either `openslide.OpenSlide` or `tiffslide.TiffSlide`).
=> fix backend setting
